# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KotlinNativeBug' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    # Your 'node_modules' directory is probably in the root of your project,
    # but if not, adjust the `:path` accordingly
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'CxxBridge',
        'DevSupport',
        'RCTBlob',
        'RCTImage',
        'RCTNetwork',
        'RCTLinkingIOS',
        'RCTSettings',
        'RCTText',
        'RCTWebSocket',
        'RCTAnimation',
        'RCTPushNotification',
        'RCTActionSheet',
        # Add any other subspecs you want to use in your project
    ]

    # Explicitly include Yoga if you are using RN >= 0.42.0
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs'
  # Pods for KotlinNativeBug
  pod 'SharedLib', :path => '../SharedLib'

  target 'KotlinNativeBugTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'KotlinNativeBug-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KotlinNativeBug-tvOS

  target 'KotlinNativeBug-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
